# PLACEHOLDER: module variables.tf not provided in screenshots.
## file system variables

variable "availability_zone_name" {
  description = "The AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes"
  type        = string
  default     = null
}

variable "name" {
  description = "The name of the file system"
  type        = string
}

variable "creation_token" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform"
  type        = string
  default     = null
}

variable "performance_mode" {
  description = "The file system performance mode. Can be either `generalPurpose` or `maxIO`. Default is `generalPurpose`"
  type        = string
  default     = "generalPurpose"

  validation {
    condition     = contains(["generalPurpose", "maxIO"], var.performance_mode)
    error_message = "The file system performance mode. Can be either `generalPurpose` or `maxIO`"
  }
}

variable "throughput_mode" {
  description = "The throughput mode for the file system. Defaults to `bursting`. Valid values: `bursting`, `elastic`, and `provisioned`. When using `provisioned`, also set `provisioned_throughput_in_mibps`"
  type        = string
  default     = "bursting"

  validation {
    condition     = contains(["bursting", "elastic", "provisioned"], var.throughput_mode)
    error_message = "Valid values: `bursting`, `elastic`, and `provisioned`"
  }
}

variable "provisioned_throughput_in_mibps" {
  description = "The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with `throughput_mode` set to `provisioned`"
  type        = number
  default     = null
}

variable "kms_key_arn" {
  description = "The ARN for the KMS encryption key. When specifying `kms_key_arn`, encrypted needs to be set to `true`"
  type        = string
}

variable "lifecycle_policy" {
  description = "A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object"
  type = object({
    transition_to_ia                    = optional(list(string), [])
    transition_to_archive               = optional(list(string), [])
    transition_to_primary_storage_class = optional(list(string), [])
  })
  default = {}
}

variable "replication_overwrite" {
  type        = string
  description = "The status of the file system's replication overwrite protection"
  default     = "ENABLED"

  validation {
    condition     = contains(["ENABLED", "DISABLED", "REPLICATING"], var.replication_overwrite)
    error_message = "Valid values: ENABLED, DISABLED, REPLICATING"
  }
}

variable "tags" {
  type        = map(string)
  description = "A map of tags to assign to the resource."
  default     = {}
}

## file system policy variables

variable "efs_file_system_policy" {
  type        = any
  description = "EFS policy to attach."
  default     = {}
}

variable "bypass_policy_lockout_safety_check" {
  type        = bool
  description = "A flag to indicate whether to bypass the `aws_efs_file_system_policy` lockout safety check."
  default     = false
}

## mount target

variable "mount_targets" {
  description = "A map of mount target definitions to create"
  type = object({
    subnets           = list(string)
    security_group_id = list(string)
  })
  default = null
}

variable "mount_target_ip_address" {
  type        = string
  description = "The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target"
  default     = null
}

## access point

variable "access_points" {
  description = "A map of access point definitions to create"
  type        = any
  default     = {}
}

## Backup policy

variable "enable_backup_policy" {
  description = "Determines whether a backup policy is `ENABLED` or `DISABLED`"
  type        = bool
  default     = true
}

## Replication Configuration

variable "replication_configuration_destination" {
  description = "A destination configuration block include values such as Region, AZ, KMS key"
  type = list(object({
    availability_zone_name = optional(string)
    region                 = optional(string)
    kms_key_id             = optional(string)
  }))
  default = []
}
