#!/usr/bin/env python3
"""
Unit tests for terraform-aws-sqs module — SecureTransport policy logic.

Validates that the policy document structure generated by the module when
enable_secure_transport=true is correctly formed and that the compliance
evaluation logic correctly distinguishes compliant vs non-compliant policies.

No AWS credentials required — pure Python, zero external dependencies.

Run:
    python3 test_policy_unit.py
"""

import json
import sys


###############################################################################
# Policy builder — mirrors the aws_iam_policy_document in main.tf
###############################################################################

def build_secure_transport_policy(queue_arn: str) -> dict:
    """
    Reconstruct the exact policy JSON the module generates when
    enable_secure_transport=true. Used as the reference 'good' policy.
    """
    return {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "DenyNonSecureTransport",
                "Effect": "Deny",
                "Principal": {"AWS": "*"},
                "Action": ["sqs:*"],
                "Resource": queue_arn,
                "Condition": {
                    "Bool": {
                        "aws:SecureTransport": "false"
                    }
                }
            }
        ]
    }


###############################################################################
# Compliance evaluation helpers — mirror what a config rule would check
###############################################################################

SECURE_TRANSPORT_CONDITION_KEYS = {"aws:securetransport"}  # lower-cased for comparison
SECURE_TRANSPORT_CONDITION_TESTS = {"bool", "boolIfExists"}
SQS_WILDCARD_ACTIONS = {"sqs:*", "*"}


def _get_deny_statements(policy: dict) -> list:
    """Return all Deny-effect statements in the policy."""
    return [s for s in policy.get("Statement", []) if s.get("Effect") == "Deny"]


def _statement_has_secure_transport_condition(stmt: dict) -> bool:
    """
    Return True when the statement has a Condition that checks
    aws:SecureTransport = 'false' (case-insensitive on the test name).
    """
    for test_name, pairs in stmt.get("Condition", {}).items():
        if test_name.lower() in {t.lower() for t in SECURE_TRANSPORT_CONDITION_TESTS}:
            for key, value in pairs.items():
                if key.lower() == "aws:securetransport" and str(value).lower() == "false":
                    return True
    return False


def _statement_covers_sqs_actions(stmt: dict) -> bool:
    """Return True when the statement covers sqs:* or the catch-all *."""
    action = stmt.get("Action", [])
    if isinstance(action, str):
        action = [action]
    return bool(SQS_WILDCARD_ACTIONS.intersection(a.lower() for a in action))


def _statement_covers_all_principals(stmt: dict) -> bool:
    """Return True when the Principal is a wildcard (AWS: *)."""
    principal = stmt.get("Principal", {})
    if principal == "*":
        return True
    if isinstance(principal, dict):
        aws = principal.get("AWS", [])
        if isinstance(aws, str):
            aws = [aws]
        return "*" in aws
    return False


def evaluate_policy_compliance(policy: dict) -> tuple[bool, str]:
    """
    Return (is_compliant, reason).
    Compliant = at least one Deny statement that:
      - covers aws:SecureTransport=false
      - covers sqs:* or *
      - applies to all principals
    """
    deny_stmts = _get_deny_statements(policy)
    if not deny_stmts:
        return False, "No Deny statements found in policy"

    for stmt in deny_stmts:
        if (
            _statement_covers_sqs_actions(stmt)
            and _statement_has_secure_transport_condition(stmt)
            and _statement_covers_all_principals(stmt)
        ):
            return True, f"Compliant deny found in statement '{stmt.get('Sid', '<no-sid>')}'"

    return False, "Deny statements exist but none correctly enforces SecureTransport on sqs:* for all principals"


###############################################################################
# Test runner
###############################################################################

_PASS_COUNT = 0
_FAIL_COUNT = 0
_QUEUE_ARN = "arn:aws:sqs:us-east-2:123456789012:test-account-simple-sqs-dev-orders"


def run_test(name: str, fn) -> bool:
    global _PASS_COUNT, _FAIL_COUNT
    print(f"\n{'='*60}")
    print(f"Test: {name}")
    print("="*60)
    try:
        fn()
        print(f"  PASSED")
        _PASS_COUNT += 1
        return True
    except AssertionError as exc:
        print(f"  FAILED — {exc}")
        _FAIL_COUNT += 1
        return False
    except Exception as exc:
        print(f"  ERROR — {type(exc).__name__}: {exc}")
        _FAIL_COUNT += 1
        return False


###############################################################################
# Tests — correct module output (enable_secure_transport=true)
###############################################################################

def test_module_policy_has_one_statement():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    assert len(policy["Statement"]) == 1, (
        f"Expected 1 statement, got {len(policy['Statement'])}"
    )


def test_module_policy_statement_sid():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    sid = policy["Statement"][0]["Sid"]
    assert sid == "DenyNonSecureTransport", f"Unexpected Sid: {sid}"


def test_module_policy_effect_is_deny():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    effect = policy["Statement"][0]["Effect"]
    assert effect == "Deny", f"Expected Deny, got {effect}"


def test_module_policy_principal_is_wildcard():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    principal = policy["Statement"][0]["Principal"]
    assert principal == {"AWS": "*"}, f"Expected wildcard principal, got {principal}"


def test_module_policy_action_is_sqs_wildcard():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    action = policy["Statement"][0]["Action"]
    assert "sqs:*" in action, f"Expected sqs:* in action, got {action}"


def test_module_policy_condition_test_is_bool():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    condition = policy["Statement"][0]["Condition"]
    assert "Bool" in condition, f"Expected 'Bool' condition test, got keys: {list(condition.keys())}"


def test_module_policy_condition_key_is_secure_transport():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    bool_block = policy["Statement"][0]["Condition"]["Bool"]
    assert "aws:SecureTransport" in bool_block, (
        f"Expected 'aws:SecureTransport' key, got: {list(bool_block.keys())}"
    )


def test_module_policy_condition_value_is_false():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    value = policy["Statement"][0]["Condition"]["Bool"]["aws:SecureTransport"]
    assert str(value).lower() == "false", (
        f"Expected condition value 'false', got '{value}'. "
        "Must be 'false' (string) so the Deny fires when SecureTransport IS false."
    )


def test_module_policy_resource_is_queue_arn():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    resource = policy["Statement"][0]["Resource"]
    assert resource == _QUEUE_ARN, f"Policy resource should be the queue ARN, got: {resource}"


def test_module_policy_is_compliant():
    policy = build_secure_transport_policy(_QUEUE_ARN)
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert is_compliant, f"Module policy should be compliant but: {reason}"


###############################################################################
# Tests — policy serialisation round-trip
###############################################################################

def test_policy_json_round_trip():
    """Policy must survive JSON serialise → deserialise without mutation."""
    policy = build_secure_transport_policy(_QUEUE_ARN)
    serialised = json.dumps(policy)
    deserialised = json.loads(serialised)
    is_compliant, reason = evaluate_policy_compliance(deserialised)
    assert is_compliant, f"Policy failed compliance after JSON round-trip: {reason}"


###############################################################################
# Tests — non-compliant policy shapes (should all fail evaluation)
###############################################################################

def test_no_policy_is_non_compliant():
    """A queue with no policy attached has no deny — non-compliant."""
    is_compliant, reason = evaluate_policy_compliance({"Version": "2012-10-17", "Statement": []})
    assert not is_compliant, "Empty policy should be non-compliant"


def test_allow_only_policy_is_non_compliant():
    """An Allow-only policy has no Deny — non-compliant."""
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "AllowAll",
            "Effect": "Allow",
            "Principal": {"AWS": "*"},
            "Action": ["sqs:*"],
            "Resource": _QUEUE_ARN
        }]
    }
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert not is_compliant, f"Allow-only policy should be non-compliant. Reason: {reason}"


def test_deny_wrong_action_is_non_compliant():
    """Deny on a non-SQS action does not enforce transport — non-compliant."""
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyWrongService",
            "Effect": "Deny",
            "Principal": {"AWS": "*"},
            "Action": ["s3:GetObject"],
            "Resource": _QUEUE_ARN,
            "Condition": {"Bool": {"aws:SecureTransport": "false"}}
        }]
    }
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert not is_compliant, "Deny on wrong action should be non-compliant"


def test_deny_wrong_condition_key_is_non_compliant():
    """Deny with a different condition key does not enforce transport — non-compliant."""
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyWrongCondition",
            "Effect": "Deny",
            "Principal": {"AWS": "*"},
            "Action": ["sqs:*"],
            "Resource": _QUEUE_ARN,
            "Condition": {"StringEquals": {"aws:RequestedRegion": "us-east-1"}}
        }]
    }
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert not is_compliant, "Deny with wrong condition key should be non-compliant"


def test_deny_condition_value_true_is_non_compliant():
    """
    Deny when aws:SecureTransport=true blocks HTTPS callers — logically wrong.
    This is a common misconfiguration.
    """
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenySecureTransport",
            "Effect": "Deny",
            "Principal": {"AWS": "*"},
            "Action": ["sqs:*"],
            "Resource": _QUEUE_ARN,
            "Condition": {"Bool": {"aws:SecureTransport": "true"}}
        }]
    }
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert not is_compliant, (
        "Deny on SecureTransport=true is a misconfiguration (blocks HTTPS callers) "
        "and should not count as compliant enforcement"
    )


def test_deny_restricted_principal_is_non_compliant():
    """
    Deny scoped to a specific IAM role does not enforce transport for all callers.
    A wildcard principal is required.
    """
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyOneRole",
            "Effect": "Deny",
            "Principal": {"AWS": "arn:aws:iam::123456789012:role/some-role"},
            "Action": ["sqs:*"],
            "Resource": _QUEUE_ARN,
            "Condition": {"Bool": {"aws:SecureTransport": "false"}}
        }]
    }
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert not is_compliant, "Deny limited to a specific principal should not be compliant"


###############################################################################
# Tests — alternative but valid compliant shapes
###############################################################################

def test_action_wildcard_star_is_compliant():
    """Action=* (catches all services including SQS) is also valid."""
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyInsecureAll",
            "Effect": "Deny",
            "Principal": {"AWS": "*"},
            "Action": ["*"],
            "Resource": _QUEUE_ARN,
            "Condition": {"Bool": {"aws:SecureTransport": "false"}}
        }]
    }
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert is_compliant, f"Action=* should be compliant: {reason}"


def test_bool_if_exists_condition_is_compliant():
    """BoolIfExists is also accepted — covers cases where the key may be absent."""
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyInsecureTransport",
            "Effect": "Deny",
            "Principal": {"AWS": "*"},
            "Action": ["sqs:*"],
            "Resource": _QUEUE_ARN,
            "Condition": {"BoolIfExists": {"aws:SecureTransport": "false"}}
        }]
    }
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert is_compliant, f"BoolIfExists condition should be compliant: {reason}"


def test_principal_wildcard_string_is_compliant():
    """Principal='*' (string, not dict) is also a wildcard."""
    policy = {
        "Version": "2012-10-17",
        "Statement": [{
            "Sid": "DenyInsecure",
            "Effect": "Deny",
            "Principal": "*",
            "Action": ["sqs:*"],
            "Resource": _QUEUE_ARN,
            "Condition": {"Bool": {"aws:SecureTransport": "false"}}
        }]
    }
    is_compliant, reason = evaluate_policy_compliance(policy)
    assert is_compliant, f"Principal='*' string should be compliant: {reason}"


###############################################################################
# Main
###############################################################################

def main() -> int:
    global _PASS_COUNT, _FAIL_COUNT

    print("\n" + "="*60)
    print("terraform-aws-sqs — Policy Unit Test Suite")
    print("No AWS credentials required")
    print("="*60)

    tests = [
        # Module output structure
        ("Module policy has one statement",                 test_module_policy_has_one_statement),
        ("Module policy statement Sid is correct",          test_module_policy_statement_sid),
        ("Module policy Effect is Deny",                    test_module_policy_effect_is_deny),
        ("Module policy Principal is wildcard",             test_module_policy_principal_is_wildcard),
        ("Module policy Action is sqs:*",                   test_module_policy_action_is_sqs_wildcard),
        ("Module policy Condition test is Bool",            test_module_policy_condition_test_is_bool),
        ("Module policy Condition key is aws:SecureTransport", test_module_policy_condition_key_is_secure_transport),
        ("Module policy Condition value is 'false'",        test_module_policy_condition_value_is_false),
        ("Module policy Resource is queue ARN",             test_module_policy_resource_is_queue_arn),
        ("Module policy passes compliance evaluation",      test_module_policy_is_compliant),
        # Round-trip
        ("Policy survives JSON serialisation round-trip",   test_policy_json_round_trip),
        # Non-compliant shapes
        ("Empty policy is non-compliant",                   test_no_policy_is_non_compliant),
        ("Allow-only policy is non-compliant",              test_allow_only_policy_is_non_compliant),
        ("Deny on wrong action is non-compliant",           test_deny_wrong_action_is_non_compliant),
        ("Deny on wrong condition key is non-compliant",    test_deny_wrong_condition_key_is_non_compliant),
        ("Deny on SecureTransport=true is non-compliant",   test_deny_condition_value_true_is_non_compliant),
        ("Deny scoped to specific principal is non-compliant", test_deny_restricted_principal_is_non_compliant),
        # Alternative valid shapes
        ("Action=* wildcard is compliant",                  test_action_wildcard_star_is_compliant),
        ("BoolIfExists condition is compliant",             test_bool_if_exists_condition_is_compliant),
        ("Principal='*' string is compliant",               test_principal_wildcard_string_is_compliant),
    ]

    for name, fn in tests:
        run_test(name, fn)

    print("\n" + "="*60)
    print("Unit Test Summary")
    print("="*60)

    total = _PASS_COUNT + _FAIL_COUNT
    for _ in range(_PASS_COUNT):
        pass  # already counted in run_test

    # Re-collect for summary line
    print(f"Total: {_PASS_COUNT}/{total} passed")

    if _FAIL_COUNT == 0:
        print("\nAll unit tests passed!")
        return 0
    else:
        print(f"\n{_FAIL_COUNT} unit test(s) failed")
        return 1


if __name__ == "__main__":
    sys.exit(main())

