###############################################################################
#                                                                             #
#   ####  STOP - EXAMPLE ONLY.  DO NOT COPY THIS FILE INTO APP CODE.  ####    #
#                                                                             #
#   THIS ENTIRE FILE EXISTS SO THAT `terraform apply` ON THE EXAMPLE WORKS    #
#   WITHOUT A REAL IDENTITY PROVIDER. IT IS *NOT* A PATTERN FOR APPLICATION   #
#   TEAMS AND MUST NEVER BE COPIED INTO AN APPLICATION REPOSITORY.            #
#                                                                             #
#   WHAT APPLICATION TEAMS DO INSTEAD:                                        #
#     1. Get the metadata XML from your REAL IdP (Azure AD / Entra ID, Okta,  #
#        PingFederate, ADFS ...). The IdP owns the signing key - you never    #
#        generate it.                                                         #
#     2. Commit that file (or fetch it from the IdP's metadata URL).          #
#     3. Point the module straight at it:                                     #
#                                                                             #
#          samlmetadatafile = "${path.module}/files/metadata.xml"             #
#                                                                             #
#        No tls_private_key. No tls_self_signed_cert. No local_file. No       #
#        `.id == "" ? ... :` trick - that whole dance only exists because     #
#        this example generates the file at apply time.                       #
#                                                                             #
#   WHY THIS IS NOT SAFE FOR APPLICATIONS:                                    #
#     - The SAML private key is generated by Terraform and stored IN PLAIN    #
#       TEXT in state. Anyone with state access can forge SAML assertions     #
#       and impersonate any user in the pool.                                 #
#     - The certificate is self-signed and trusted by nobody.                 #
#     - idp.example.com is not a real IdP. No one can actually log in.        #
#                                                                             #
###############################################################################
# Why the example does it this way at all:
#
# The example previously shipped a static metadata.xml whose signing
# certificate had expired, so `terraform apply` failed inside Cognito. Instead
# of committing another certificate with a fixed expiry, the example mints a
# throwaway self-signed certificate on every run with the `tls` provider,
# renders the IdP metadata around it, and writes it to disk for the module to
# read. The module itself is unchanged.
#
# Nothing here is a real identity provider: the entity ID and SSO URL point at
# example.com, and the private key lives only in this example's state.
###############################################################################

# EXAMPLE ONLY - DO NOT DO THIS IN APPLICATION CODE.
# A real SAML signing key is generated and held by the IdP, never by Terraform.
# This key is written to state in plaintext; treat it as compromised the moment
# it is created. It is disposable because nothing real trusts it.
resource "tls_private_key" "saml_signing" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

# EXAMPLE ONLY - DO NOT DO THIS IN APPLICATION CODE.
# Replace this whole resource with metadata from your real IdP. A self-signed
# certificate is not an identity provider; it only satisfies Cognito's
# validation so the example can be applied.
resource "tls_self_signed_cert" "saml_signing" {
  private_key_pem = tls_private_key.saml_signing.private_key_pem

  subject {
    common_name  = local.saml_entity_id
    organization = "Terraform AWS Cognito Example - NOT FOR APPLICATION USE"
  }

  # Long-lived on purpose: the point of generating it here is that the example
  # never goes stale the way the committed certificate did.
  validity_period_hours = 87600 # 10 years
  early_renewal_hours   = 720   # regenerate 30 days before expiry

  allowed_uses = [
    "digital_signature",
    "cert_signing",
  ]
}

locals {
  # EXAMPLE ONLY - fake IdP endpoints. Nothing is served at these URLs. In an
  # application, these values come from your real IdP's metadata, which you do
  # not hand-assemble.
  saml_entity_id = "https://idp.example.com/metadata"
  saml_sso_url   = "https://idp.example.com/sso"

  # SAML metadata carries the bare base64 DER body, without the PEM armor.
  # EXAMPLE ONLY - application code never has to do this, because a real IdP
  # hands you finished metadata with the certificate already embedded.
  saml_signing_certificate = replace(
    tls_self_signed_cert.saml_signing.cert_pem,
    "/-----(BEGIN|END) CERTIFICATE-----|\\n/",
    "",
  )

  # EXAMPLE ONLY - an application points `samlmetadatafile` at the real
  # metadata file on disk; it does not render metadata from a template.
  saml_metadata = templatefile("${path.module}/files/metadata.xml.tftpl", {
    entity_id           = local.saml_entity_id
    sso_url             = local.saml_sso_url
    signing_certificate = local.saml_signing_certificate
  })
}

###############################################################################
# Hand the rendered metadata to the module
#
# The module reads its metadata from disk via `data "local_file"`, so the
# rendered XML has to become a real file first.
#
# EXAMPLE ONLY - DO NOT DO THIS IN APPLICATION CODE. An application already
# HAS a metadata file (the one its IdP gave it), so there is nothing to write
# at apply time and this resource has no place in an application repo.
# Writing it here is also what forces the `.id == "" ? ...` workaround on the
# module call - delete this resource in your own code and that goes away too.
###############################################################################

resource "local_file" "saml_metadata" {
  filename = "${path.module}/generated/metadata.xml"
  content  = local.saml_metadata

  # Generated at apply time and gitignored - it is derived state, not source.
}
