Resources:
EbsIsEncryptedsx45:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: erieins-operations-dev-ebs-is-encrypted-sx45
      Description: Config Rule for checking if an EBS Volume is encrypted
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Volume
      Source:
        Owner: CUSTOM_POLICY
        SourceDetails:
          EventSource: aws.config
          MessageType: ConfigurationItemChangeNotification
      CustomPolicyDetails:
        PolicyRuntime: guard-2.x.x
        PolicyText: |
        rule ebsSnapshotIsEncrypted when resourceType == "AWS::EC2::Snapshot" {
              configuration.encrypted == true <<EBS snapshots must be encrypted at rest>>
        }

SqsIsEncryptedsx45:
  Type: AWS::Config::ConfigRule
  Properties:
    ConfigRuleName: erieins-operations-dev-sqs-is-encrypted-sx45
    Description: Config Rule for checking if an SQS Queue is encrypted
    Scope:
      ComplianceResourceTypes:
        - AWS::SQS::Queue
    Source:
      Owner: CUSTOM_POLICY
      SourceDetails:
        EventSource: aws.config
        MessageType: ConfigurationItemChangeNotification
      CustomPolicyDetails:
        PolicyRuntime: guard-2.x.x
        PolicyText: |
              rule sqsIsEncrypted when resourceType == "AWS::SQS::Queue" {
              configuration.SqsManagedSseEnabled == "true" <<SQS's must be encrypted>>
       }

  EfsIsEncryptedsx45:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: erieins-operations-dev-efs-is-encrypted-sx45
      Description: Config Rule for checking if an EFS is encrypted
      Scope:
        ComplianceResourceTypes:
          - AWS::EFS::FileSystem
      Source:
        Owner: CUSTOM_POLICY
        SourceDetails:
          EventSource: aws.config
          MessageType: ConfigurationItemChangeNotification
      CustomPolicyDetails:
        PolicyRuntime: guard-2.x.x
        PolicyText: |
              rule efsIsEncrypted when resourceType == "AWS::EFS::FileSystem" {
              configuration.Encrypted == true <<EFS's must be encrypted>>
       }

  EfsTlsEnforcementsx45:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: erieins-operations-dev-efs-tls-enforcement-sx45
      Description: Custom Lambda rule to validate EFS file system policies enforce TLS (aws:SecureTransport)
      Scope:
        ComplianceResourceTypes:
          - AWS::EFS::FileSystem
      Source:
        Owner: CUSTOM_LAMBDA
        SourceDetails:
          - EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
        SourceIdentifier: arn:aws:lambda:us-east-2:637423432759:function:erieins-operations-dev-efs-tls-enforcement-dev